Repository CS3203-Team-6/SPA, pull requests merged in 2019-02, with the labels that each got.

#28 Iteration 1.1 : Add Lexical Token Verification and some test cases.
  Code/AutoTester/AutoTester.vcxproj
  Code/AutoTester/source/TestWrapper.cpp
  Code/Gui/GeneratedFiles/ui_mainwindow.h
  Code/Gui/Gui.vcxproj
  Code/IntegrationTesting/IntegrationTesting.vcxproj
  Code/SPA/AssignParser.cpp
  Code/SPA/AssignParser.h
  Code/SPA/SPA.vcxproj
  Code/SPA/SPA.vcxproj.filters
  Code/UnitTesting/LexicalTokenTest.cpp
  Code/UnitTesting/UnitTesting.vcxproj
  Code/UnitTesting/UnitTesting.vcxproj.filters
  Code/source/LexicalToken.cpp
  Code/source/LexicalToken.h
  Code/source/Parser.h
Labels: Front-End, enhancement

#29 Iteration 1.1: Parsing Declarations
  Code/SPA/SPA.vcxproj
  Code/SPA/SPA.vcxproj.filters
  Code/UnitTesting/QueryParserTest.cpp
  Code/UnitTesting/UnitTesting.vcxproj
  Code/UnitTesting/UnitTesting.vcxproj.filters
  Code/source/QueryParser.cpp
  Code/source/QueryParser.h
Labels: PQL, enhancement

#32 [Iteration 1.2] Hotfix for AssignParserTest
  Code/SPA/SPA.vcxproj
  Code/SPA/SPA.vcxproj.filters
  Code/UnitTesting/AssignParserTest.cpp
  Code/source/AssignParser.cpp
  Code/source/AssignParser.h
  Code/source/StringUtil.cpp
Labels: Front-End, bug

#38 Iteration 1.3 : ExpressionUtil and some fixes to old components.
  Code/UnitTesting/ExpressionUtilTest.cpp
  Code/UnitTesting/LexicalTokenTest.cpp
  Code/UnitTesting/TestAST.cpp
  Code/UnitTesting/UnitTesting.vcxproj
  Code/UnitTesting/UnitTesting.vcxproj.filters
  Code/source/ExpressionUtil.cpp
  Code/source/ExpressionUtil.h
  Code/source/LexicalToken.cpp
  Code/source/LexicalToken.h
Labels: Front-End, PQL

#37 Iteration 1: Query Validation
  Code/UnitTesting/QueryParserTest.cpp
  Code/source/QueryParser.cpp
  Code/source/QueryParser.h
Labels: PQL, Testing

#39 PKB implementation with tables and list & PostProcessor
  .gitignore
  Code/AutoTester/AutoTester.vcxproj
  Code/Gui/Gui.vcxproj
  Code/IntegrationTesting/IntegrationTesting.vcxproj
  Code/SPA/SPA.vcxproj
  Code/SPA/SPA.vcxproj.filters
  Code/UnitTesting/UnitTesting.vcxproj
  Code/UnitTesting/UnitTesting.vcxproj.filters
  Code/source/DesignExtractor.cpp
  Code/source/FollowStorage.cpp
  Code/source/FollowStorage.h
  Code/source/Hasher.h
  Code/source/ModifyStorage.cpp
  Code/source/ModifyStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
  Code/source/ParentStorage.cpp
  Code/source/ParentStorage.h
  Code/source/PostProcessor.cpp
  Code/source/PostProcessor.h
  Code/source/TNode.cpp
  Code/source/TNode.h
  Code/source/UseStorage.cpp
  Code/source/UseStorage.h
Labels: Front-End, PKB, enhancement

#42 Iteration 1.4 : Parser and Integration with Specific Statement Parsers
  Code/SPA/SPA.vcxproj
  Code/SPA/SPA.vcxproj.filters
  Code/UnitTesting/AssignParserTest.cpp
  Code/UnitTesting/ExpressionUtilTest.cpp
  Code/source/AssignParser.cpp
  Code/source/AssignParser.h
  Code/source/ExpressionUtil.cpp
  Code/source/Parser.cpp
  Code/source/Parser.h
  Code/source/QueryParser.cpp
  Code/source/Statement.cpp
Labels: Front-End

#49 Constant now a string
  .gitignore
  Code/SPA/SPA.vcxproj
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: bug

#51 Add AutoTester files
  Tests/queries1.txt
  Tests/source2.txt
Labels: Testing

#57 bugfix for simple program with only 1 procedure
  Code/source/Preprocesser.cpp
Labels: bug

#56 Add unit tests and C++docs(?) to for QueryEvaluator methods + bug fixing
  Code/UnitTesting/QueryEvaluatorTest.cpp
  Code/UnitTesting/UnitTesting.vcxproj
  Code/UnitTesting/UnitTesting.vcxproj.filters
  Code/source/QueryEvaluator.cpp
Labels: PQL, Testing, bug

#58 Initialized static member
  Code/source/PostProcessor.cpp
Labels: bug
