Repository CS3203-Team-6/SPA, pull requests merged in 2019-04, with the labels that each got.

#138 Iteration 2 : PKB While/If Control Variable Storage
  Code/SPA/SPA.vcxproj
  Code/SPA/SPA.vcxproj.filters
  Code/source/ControlVariableStorage.cpp
  Code/source/ControlVariableStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
  Code/source/Parser.cpp
Labels: PKB, enhancement

#142 Iteration 2 : PKB Changes to accomodate PQL.
  Code/source/ControlVariableStorage.cpp
  Code/source/ControlVariableStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: PKB, enhancement

#144 Fix wrong testcases result and add tuple queries
  Tests/system-tests-1/Calls.txt
  Tests/system-tests-1/CallsStar.txt
  Tests/system-tests-1/Tuples.txt
Labels: Testing, bug

#148 System testing files, queries for NextStar
  Tests/system-tests-1/NextStar.txt
Labels: Testing

#147 Add Next* for two synonyms
  Code/UnitTesting/NextStartTest.cpp
  Code/source/PKB.cpp
  Code/source/RunTimeDesignExtractor.cpp
  Code/source/RunTimeDesignExtractor.h
Labels: Front-End, enhancement

#152 Fix Bugs for Next Relationship
  Code/source/Parser.cpp
Labels: Front-End, bug

#150 Query bugfixes
  Code/source/QueryEvaluator.cpp
  Code/source/QueryParser.cpp
  Tests/system-tests-1/Boolean.txt
  Tests/system-tests-1/Next.txt
  Tests/system-tests-1/Tuples.txt
Labels: Testing, bug

#153 Multiple conditions queries - easy
  Tests/system-tests-1/Multiple-easy.txt
Labels: Testing

#155 System testing files - queries for Uses
  Tests/system-tests-1/Pattern.txt
  Tests/system-tests-1/Uses.txt
  Tests/system-tests-1/Uses1.txt
Labels: Testing

#140 Created erase method for PKB
  Code/source/CallStorage.cpp
  Code/source/CallStorage.h
  Code/source/FollowStorage.cpp
  Code/source/FollowStorage.h
  Code/source/ModifyStorage.cpp
  Code/source/ModifyStorage.h
  Code/source/NextStorage.cpp
  Code/source/NextStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
  Code/source/ParentStorage.cpp
  Code/source/ParentStorage.h
  Code/source/RunTimeDesignExtractor.cpp
  Code/source/RunTimeDesignExtractor.h
  Code/source/UseStorage.cpp
  Code/source/UseStorage.h
Labels: PKB, enhancement

#160 Fix Conditional Expression parsing tabs as variable
  Code/source/ConditionalExp.cpp
Labels: bug

#161 Changed order of checks for addCall and have it return void
  Code/source/CallStorage.cpp
  Code/source/CallStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: PKB

#164 New Methods
  .gitignore
  Code/source/PKB.cpp
  Code/source/PKB.h
  Tests/system-tests-1/Uses_Randy.txt
Labels: PKB, enhancement

#166 Fix Bugs for Next
  Code/IntegrationTesting/DesignExtractorPKBTest.cpp
  Code/UnitTesting/NextStartTest.cpp
  Code/source/DesignExtractor.cpp
  Code/source/DesignExtractor.h
  Code/source/Parser.cpp
  Code/source/Parser.h
  Tests/system-tests-1/Next.txt
Labels: Front-End, bug

#168 Fix iteration 2 wrong queries
  Tests/system-tests-1/Pattern.txt
  Tests/system-tests-1/WithClause.txt
Labels: Testing, bug

#169 add select attribute synonym (independent and tuples)
  Code/UnitTesting/QueryParserTest.cpp
  Code/UnitTesting/QueryValidatorTest.cpp
  Code/source/QueryValidator.cpp
Labels: PQL, enhancement

#163 Iteration 3 PQL Optimiser
  Code/SPA/SPA.vcxproj
  Code/SPA/SPA.vcxproj.filters
  Code/UnitTesting/OptimizerTest.cpp
  Code/UnitTesting/OptimizerUtilityTest.cpp
  Code/UnitTesting/UnitTesting.vcxproj
  Code/UnitTesting/UnitTesting.vcxproj.filters
  Code/source/Optimizer.cpp
  Code/source/Optimizer.h
  Code/source/OptimizerUtility.cpp
  Code/source/OptimizerUtility.h
Labels: PQL

#175 Bugfixes for Optimizer
  Code/UnitTesting/PQL/OptimizerTest.cpp
  Code/UnitTesting/Utility/OptimizerUtilityTest.cpp
  Code/source/Optimizer.cpp
  Code/source/Optimizer.h
  Code/source/OptimizerUtility.cpp
  Code/source/OptimizerUtility.h
Labels: bug

#174 Add system test 2 source file (different nesting level)
  Tests/system-tests-2/source-nesting-numbered.txt
  Tests/system-tests-2/source-nesting.txt
Labels: Testing

#176 Source 2 testcases
  .gitignore
  Code/source/QueryParser.cpp
  Tests/system-tests-1/WithClause.txt
  Tests/system-tests-1/runAllQueries.bat
  Tests/system-tests-2/Calls.txt
  Tests/system-tests-2/CallsStar.txt
Labels: Testing

#179 Queries for source 1 - Follows
  .gitignore
  Tests/system-tests-1/Follows.txt
Labels: Testing

#167 Front end Affects/Affects*
  Code/IntegrationTesting/DesignExtractorPKBTest.cpp
  Code/UnitTesting/Utility/ExpressionUtilTest.cpp
  Code/source/PKB.cpp
  Code/source/RunTimeDesignExtractor.cpp
  Code/source/RunTimeDesignExtractor.h
Labels: Front-End, enhancement

#173 storing of if and while stmLists
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: PKB, enhancement

#184 Fix Bug for ConditionalExp and Next
  Code/source/ConditionalExp.cpp
  Code/source/Parser.cpp
Labels: bug

#180 Source 1 queries - follows*
  Tests/system-tests-1/FollowsStar.txt
  Tests/system-tests-2/source-nesting-numbered.txt
  Tests/system-tests-2/source-nesting.txt
Labels: Testing

#185 UnitTesting & Affects/* Integration
  Code/UnitTesting/DesignExtractor/NextStarTest.cpp
  Code/UnitTesting/PKB/CallStorageTest.cpp
  Code/UnitTesting/PKB/CtrlVarStorageStub.h
  Code/UnitTesting/PKB/CtrlVarStorageTest.cpp
  Code/UnitTesting/PKB/FollowStorageStub.h
  Code/UnitTesting/PKB/FollowStorageTest.cpp
  Code/UnitTesting/PKB/ModifyStorageStub.h
  Code/UnitTesting/PKB/ModifyStorageTest.cpp
  Code/UnitTesting/PKB/NextStorageTest.cpp
  Code/UnitTesting/PKB/PKBStub.h
  Code/UnitTesting/PKB/PKBTest.cpp
  Code/UnitTesting/PKB/ParentStorageStub.h
  Code/UnitTesting/PKB/ParentStorageTest.cpp
  Code/UnitTesting/PKB/UseStorageStub.h
  Code/UnitTesting/PKB/UseStorageTest.cpp
  Code/UnitTesting/UnitTesting.vcxproj
  Code/UnitTesting/UnitTesting.vcxproj.filters
  Code/source/CtrlVarStorage.cpp
  Code/source/CtrlVarStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: PKB, Testing, enhancement

#183 System test 3
  .gitignore
  Code/Tests/runAllQueries.bat
  Tests/invalid-SIMPLE-cyclic-test/emptyQueries.txt
  Tests/invalid-SIMPLE-cyclic-test/runQueries.bat
  Tests/invalid-SIMPLE-duplicateprocedure/emptyQueries.txt
  Tests/invalid-SIMPLE-duplicateprocedure/runQueries.bat
  Tests/invalid-SIMPLE-non-existantcall/emptyQueries.txt
  Tests/invalid-SIMPLE-non-existantcall/runQueries.bat
  Tests/system-tests-1/Next1.txt
  Tests/system-tests-1/NextStar.txt
  Tests/system-tests-1/NextStar1.txt
  Tests/system-tests-1/Uses.txt
  Tests/system-tests-1/Uses1.txt
  Tests/system-tests-1/Uses_Randy.txt
  Tests/system-tests-2/Affects.txt
  Tests/system-tests-2/source-nesting-numbered.txt
  Tests/system-tests-2/source-nesting.txt
  Tests/system-tests-3/Affects.txt
  Tests/system-tests-3/Calls.txt
  Tests/system-tests-3/CallsStar.txt
  Tests/system-tests-3/sourceAlphanumeric-numbered.txt
  Tests/system-tests-3/sourceAlphanumeric.txt
Labels: Testing

#195 Fix ConditionalExp bug and add some unit test
  Code/UnitTesting/Utility/ConditionalExpTest.cpp
  Code/source/ConditionalExp.cpp
Labels: bug

#201 Uses & Modifies bugfix
  .gitignore
  Code/source/QueryParser.cpp
  Code/source/QueryValidator.cpp
  Tests/system-tests-2/Parent.txt
  Tests/system-tests-2/ParentStar.txt
  Tests/system-tests-2/runAllQueries.bat
  Tests/system-tests-3/Calls.txt
  Tests/system-tests-3/CallsStar.txt
  Tests/system-tests-3/runAllQueries.bat
Labels: bug

#203 Add queries
  Code/source/QueryValidator.cpp
  Tests/system-tests-1/Parent.txt
  Tests/system-tests-1/ParentStar.txt
  Tests/system-tests-1/runAllQueries.bat
  Tests/system-tests-2/PatternAssign.txt
  Tests/system-tests-2/PatternIf.txt
  Tests/system-tests-2/PatternWhile.txt
  Tests/system-tests-2/runAllQueries.bat
Labels: Testing

#206 Add Next/NextStar test cases for system-test-1,2,3
  Tests/system-tests-1/Next.txt
  Tests/system-tests-1/NextStar.txt
  Tests/system-tests-2/Next.txt
  Tests/system-tests-2/NextStar.txt
  Tests/system-tests-3/Next.txt
  Tests/system-tests-3/NextStar.txt
Labels: Testing

#211 Add Integration test for frontEnd to PKB Next relation
  Code/IntegrationTesting/ParserPKBTest.cpp
Labels: Testing

#209 Add queries
  .gitignore
  Code/UnitTesting/PQL/QueryParserTest.cpp
  Tests/system-tests-2/With.txt
  Tests/system-tests-2/runAllQueries.bat
  Tests/system-tests-3/NoCondition.txt
  Tests/system-tests-3/runAllQueries.bat
  Tests/system-tests-4/Affects.txt
  Tests/system-tests-4/SourceAffectsProcedure-numbered.txt
  Tests/system-tests-4/SourceAffectsProcedure.txt
  Tests/system-tests-4/analysis.xsl
  Tests/system-tests-4/runAllQueries.bat
Labels: Testing

#213 Add system test queries
  Tests/system-tests-1/Boolean.txt
  Tests/system-tests-1/Modifies.txt
  Tests/system-tests-4/AffectsStar.txt
  Tests/system-tests-4/runAllQueries.bat
Labels: Testing

#218 Fix pattern errors
  Code/source/QueryParser.cpp
  Tests/system-tests-2/PatternWhile.txt
Labels: bug

#224 fix query parser infinite loop
  Code/source/QueryParser.cpp
Labels: bug

#226 Parser - PKB integration Test + changes in Unit Testing
  Code/IntegrationTesting/DesignExtractorPKBTest.cpp
  Code/IntegrationTesting/ParserPKBTest.cpp
  Code/UnitTesting/DesignExtractor/NextStarTest.cpp
  Code/UnitTesting/PKB/CallStorageStub.h
  Code/UnitTesting/PKB/CallStorageTest.cpp
  Code/UnitTesting/PKB/CtrlVarStorageStub.h
  Code/UnitTesting/PKB/CtrlVarStorageTest.cpp
  Code/UnitTesting/PKB/FollowStorageTest.cpp
  Code/UnitTesting/PKB/ModifyStorageStub.h
  Code/UnitTesting/PKB/ModifyStorageTest.cpp
  Code/UnitTesting/PKB/NextStorageStub.h
  Code/UnitTesting/PKB/NextStorageTest.cpp
  Code/UnitTesting/PKB/PKBStub.h
  Code/UnitTesting/PKB/PKBTest.cpp
  Code/UnitTesting/PKB/ParentStorageTest.cpp
  Code/UnitTesting/PKB/UseStorageStub.h
  Code/UnitTesting/PKB/UseStorageTest.cpp
  Code/source/CallStorage.cpp
  Code/source/CallStorage.h
  Code/source/CtrlVarStorage.cpp
  Code/source/CtrlVarStorage.h
  Code/source/FollowStorage.cpp
  Code/source/FollowStorage.h
  Code/source/ModifyStorage.cpp
  Code/source/ModifyStorage.h
  Code/source/NextStorage.cpp
  Code/source/NextStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
  Code/source/ParentStorage.cpp
  Code/source/ParentStorage.h
  Code/source/UseStorage.cpp
  Code/source/UseStorage.h
Labels: Front-End, PKB, Testing

#227 Iteration 3 Final WIP
  Code/IntegrationTesting/IntegrationTesting.vcxproj
  Code/IntegrationTesting/IntegrationTesting.vcxproj.filters
  Code/IntegrationTesting/ParserPKBTest.cpp
  Code/IntegrationTesting/RTDEPKBTest.cpp
  Tests/system-tests-3/PatternAssign.txt
  Tests/system-tests-3/PatternIf.txt
  Tests/system-tests-3/PatternWhile.txt
  Tests/system-tests-3/With.txt
  Tests/system-tests-3/runAllQueries.bat
Labels: Testing
