Repository CS3203-Team-6/SPA, pull requests merged in 2019-03, with the labels that each got.

#68 Query Evaluator Bugfixes
  Code/AutoTester/source/TestWrapper.cpp
  Code/source/QueryEvaluator.cpp
  Code/source/QueryParser.cpp
Labels: bug

#74 bug fix in isSuchThatTrivial function
  Code/source/QueryEvaluator.cpp
Labels: PQL, bug

#75 bugfix for preprocesser
  Code/source/Preprocesser.cpp
Labels: Front-End, bug

#76 Change return type of PQL evaluator to unordered_set
  Code/AutoTester/source/TestWrapper.cpp
  Code/UnitTesting/QueryEvaluatorTest.cpp
  Code/source/QueryEvaluator.cpp
  Code/source/QueryEvaluator.h
  Code/source/QueryParser.cpp
  Code/source/QueryParser.h
Labels: PQL

#66 Fixed bugs
  Code/source/FollowStorage.cpp
  Code/source/ModifyStorage.cpp
  Code/source/ParentStorage.cpp
  Code/source/PostProcessor.cpp
  Code/source/UseStorage.cpp
Labels: bug

#81 Changed return value
  Code/source/ModifyStorage.cpp
  Code/source/ModifyStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
  Code/source/UseStorage.cpp
Labels: PKB, PQL, bug

#80 Iteration 1.4 Fix : Add Design Extractor Logic and new Test Queries
  Code/AutoTester/source/TestWrapper.cpp
  Code/SPA/SPA.vcxproj
  Code/SPA/SPA.vcxproj.filters
  Code/Tests/queries1.txt
  Code/source/DesignExtractor.cpp
  Code/source/DesignExtractor.h
  Code/source/PostProcessor.cpp
  Code/source/PostProcessor.h
  Tests/queries1.txt
Labels: Front-End

#83 created a method findPatternPairs
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: PKB, enhancement

#85 Query Validation & Evaluation Fixes
  Code/source/QueryParser.cpp
Labels: PQL, bug

#88 Add System Test
  Code/Tests/queries3.txt
  Code/Tests/source3.txt
Labels: Testing

#87 Fix ConditionalExp
  Code/UnitTesting/ConditionalExpTest.cpp
  Code/source/ConditionalExp.cpp
  Code/source/ConditionalExp.h
Labels: Front-End, bug

#94 Fix wrong queries
  Code/Tests/queries3.txt
Labels: Testing

#100 Fix ConditionalExp to be non static
  Code/UnitTesting/ConditionalExpTest.cpp
  Code/source/ConditionalExp.cpp
  Code/source/ConditionalExp.h
Labels: Code Style, Front-End

#107 added 4th system test
  Code/Tests/queries4.txt
  Code/Tests/source4.txt
Labels: Testing

#108 Add invalid and irregular queries
  Code/Tests/irregular-queries1.txt
Labels: Testing

#111 Fix pattern clause validation
  Code/Tests/irregular-queries1.txt
  Code/Tests/queries4.txt
  Code/UnitTesting/QueryParserTest.cpp
  Code/source/QueryParser.cpp
Labels: bug

#112 Update code style
  Code/SPA/SPA.vcxproj
  Code/SPA/SPA.vcxproj.filters
  Code/UnitTesting/QueryParserTest.cpp
  Code/UnitTesting/QueryValidatorTest.cpp
  Code/UnitTesting/UnitTesting.vcxproj
  Code/UnitTesting/UnitTesting.vcxproj.filters
  Code/source/QueryParser.cpp
  Code/source/QueryParser.h
  Code/source/QueryValidator.cpp
  Code/source/QueryValidator.h
  Code/source/StringUtil.cpp
  Code/source/StringUtil.h
Labels: Code Style

#114 PQL Parser & Validator: Iteration 2.1
  Code/Tests/irregular-queries1.txt
  Code/Tests/queries1.txt
  Code/UnitTesting/QueryParserTest.cpp
  Code/UnitTesting/QueryValidatorTest.cpp
  Code/source/QueryParser.cpp
  Code/source/QueryValidator.cpp
Labels: PQL, Testing

#115 Iteration 2: Call Logic
  Code/AutoTester/source/TestWrapper.cpp
  Code/SPA/SPA.vcxproj
  Code/SPA/SPA.vcxproj.filters
  Code/UnitTesting/AssignParserTest.cpp
  Code/UnitTesting/ExpressionUtilTest.cpp
  Code/source/AssignParser.cpp
  Code/source/AssignParser.h
  Code/source/CallParser.cpp
  Code/source/CallParser.h
  Code/source/DesignExtractor.cpp
  Code/source/DesignExtractor.h
  Code/source/ElseParser.cpp
  Code/source/ElseParser.h
  Code/source/ExpressionUtil.cpp
  Code/source/ExpressionUtil.h
  Code/source/IfParser.cpp
  Code/source/IfParser.h
  Code/source/LexicalToken.cpp
  Code/source/LexicalToken.h
  Code/source/PKB.h
  Code/source/Parser.cpp
  Code/source/Parser.h
  Code/source/PrintParser.cpp
  Code/source/PrintParser.h
  Code/source/ProcedureParser.cpp
  Code/source/ProcedureParser.h
  Code/source/ReadParser.cpp
  Code/source/ReadParser.h
  Code/source/WhileParser.cpp
  Code/source/WhileParser.h
Labels: Front-End, enhancement

#117 renaming methods and fields
  Code/SPA/SPA.vcxproj.filters
  Code/source/DesignExtractor.cpp
  Code/source/FollowStorage.cpp
  Code/source/FollowStorage.h
  Code/source/ModifyStorage.cpp
  Code/source/ModifyStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
  Code/source/ParentStorage.cpp
  Code/source/ParentStorage.h
  Code/source/Parser.cpp
  Code/source/QueryEvaluator.cpp
  Code/source/UseStorage.cpp
  Code/source/UseStorage.h
Labels: Code Style, PKB, enhancement

#118 Multiple condition & "with" clause
  Code/UnitTesting/QueryParserTest.cpp
  Code/UnitTesting/QueryValidatorTest.cpp
  Code/source/QueryParser.cpp
  Code/source/QueryParser.h
  Code/source/QueryValidator.cpp
  Code/source/QueryValidator.h
Labels: PQL, enhancement

#121 Change implementation of declarations table
  Code/UnitTesting/QueryParserTest.cpp
  Code/UnitTesting/QueryValidatorTest.cpp
  Code/source/QueryParser.cpp
  Code/source/QueryParser.h
  Code/source/QueryValidator.cpp
  Code/source/QueryValidator.h
Labels: PQL, enhancement

#120 Call/Call* and Next
  Code/SPA/SPA.vcxproj
  Code/SPA/SPA.vcxproj.filters
  Code/source/CallStorage.cpp
  Code/source/CallStorage.h
  Code/source/NextStorage.cpp
  Code/source/NextStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: PKB, enhancement

#124 changed and added methods
  Code/source/CallStorage.cpp
  Code/source/CallStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: PKB, enhancement

#125 Fixed bug
  Code/source/NextStorage.cpp
  Code/source/NextStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: PKB, bug

#126 bug fix
  Code/source/NextStorage.cpp
  Code/source/NextStorage.h
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: PKB, bug

#122 Iteration 2 Calls* and Uses/Modifies for multiple procedures.
  Code/IntegrationTesting/FrontEndPKBTest.cpp
  Code/IntegrationTesting/IntegrationTesting.vcxproj
  Code/source/DesignExtractor.cpp
  Code/source/DesignExtractor.h
  Code/source/Parser.cpp
  Code/source/Parser.h
  Code/source/ProcedureParser.h
Labels: Front-End, bug, enhancement

#123 System test for demo
  Tests/queries1.txt
  Tests/source1.txt
  Tests/source2.txt
  Tests/source3.txt
  Tests/system-tests-1/Calls.txt
  Tests/system-tests-1/CallsStar.txt
  Tests/system-tests-1/sourceDemo-numbered.txt
  Tests/system-tests-1/sourceDemo.txt
Labels: Testing

#132 Bug fix
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: PKB, bug

#133 addProc now returns a bool
  Code/source/PKB.cpp
  Code/source/PKB.h
Labels: PKB

#134 individual check for inserting into procToStmMap
  Code/source/CallStorage.cpp
Labels: PKB, bug

#135 fix system test source code
  Tests/system-tests-1/sourceDemo-numbered.txt
  Tests/system-tests-1/sourceDemo.txt
Labels: Testing, bug
